### ISSUE TITLE
Can we simplify? :)

### ISSUE THREAD

**Issue by LukaszDziwosz** [KALIMI/HTTPRequest#1]
```
func fetchChats() -> AnyPublisher<ChatListModel, AFError> {
        let url = URL(string: "Your_URL")!
        
        return AF.request(url,
                          method: .get)
            .validate()
            .publishDecodable(type: ChatListModel.self)
            .value()
            .receive(on: DispatchQueue.main)
            .eraseToAnyPublisher()
    }
```
That seems to work thanks to .value() but if we have:
`func fetchChats() -> AnyPublisher<ChatListModel, NetworkError> `
then underneath .value() we would have to mapError similar as you did:
```
.map { response in
                response.mapError { error in
                    let backendError = response.data.flatMap { try? JSONDecoder().decode(BackendError.self, from: $0)}
                    return NetworkError(initialError: error, backendError: backendError)
                }
            }
```
if  under .value() we add 
```
.mapError({ error in
                <#code#>
            })
```
then error is `let error: AFError` exactly as after `response.mapError` in your code, however I fail to map it due to my poor Combine skills. Reason for all this is that with simplified function I can easily mock that function output for unit tests like so:
```
// MARK: - Mock Combine function output 

    func request<T>(configuration: RequestConfiguration) -> AnyPublisher<T, Error> where T : Decodable {

        if T.self == [Chat].self {
            return Just(mockChats as! T)
                .setFailureType(to: Error.self)
                .eraseToAnyPublisher()
        }

        return Fail(error: NSError()).eraseToAnyPublisher()
    }
```

**Comment by karenxpn** [comment]
I think it would be better to create a generic function as you did but with <T, Error> you won't be able to fetch server-side error.

    func post_patchRequest<T, P>( params: P,
                                  url: URL,
                                  method: HTTPMethod = .post,
                                  responseType: T.Type)
    -> AnyPublisher<DataResponse<T, NetworkError>, Never> where T : Decodable, P : Encodable {
        
        var headers: HTTPHeaders = ["Authorization": "Bearer \(token == "" ? initialToken : token)"]
        
        return AF.request(url,
                          method: method,
                          parameters: params,
                          encoder: JSONParameterEncoder.default,
                          headers: headers)
            .validate()
            .publishDecodable(type: T.self)
            .map { response in
                response.mapError { error in
                    let backendError = response.data.flatMap { try? JSONDecoder().decode(BackendError.self, from: $0)}
                    return NetworkError(initialError: error, backendError: backendError)
                }
            }
            .receive(on: DispatchQueue.main)
            .eraseToAnyPublisher()
    }
